kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - dotnet sonarscanner begin
        /k:"easv-devops_devOps-week6_AY4OBmngEVvRW2O60EWV"
        /d:sonar.host.url="http://sonar.setgo.dk:9000" 
        /d:sonar.token="sqp_63c0d8459c438c03e029e3138dda94ff6693c979"
        /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
        /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
        - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
        - dotnet sonarscanner end /d:sonar.token="$SONARSECRET"